security:
  user:
    password: password
  ignored: /**/favicon.ico,/js/**,/css/**
logging:
  level:
    org.springframework.security: DEBUG

zuul:
  routes:
    resource:
      sensitive-headers:
      path: /resource/**
      url: http://localhost:9000
